name: epu baal, harmcorp org.
permalink: /blog/:year/:month/:day/:title
# Conversion
markdown: kramdown
highlighter: rouge
# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
theme: jekyll-theme-minimal