#
# This file contains configuration flags to customize your site
#
name: Epu Baal # Name of your site (displayed in the header)
title: log of epu baal
description: developer from pamukkale # Short bio or description (displayed in the header)

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/epubaal.jpg

#instagram
#https://scontent-gmp1-1.cdninstagram.com/vp/a880cdd91396514b9f38dd7557a91abb/5DCF8F00/t51.2885-19/s320x320/15625473_1799036933646483_957812268609830912_a.jpg?_nc_ht=scontent-gmp1-1.cdninstagram.com
#github
#https://avatars3.githubusercontent.com/u/1744571?s=400&v=4

#
# !! cf home page !!
#
# https://shopify.github.io/liquid/
# https://jekyllrb-ko.github.io/
navigation:
  - name: Log
    url: /
  - name: About
    url: /about
  - name: Tags
    url: /tags
# File name Pattern - Tag
# shovel - shovel-knight


# Includes an icon in the footer for each username you enter
# image circle-crop : http://crop-circle.imageonline.co/#circlecropresult
# base63 encode/decode : http://freeonlinetools24.com/base64-image
footer-links:
  dribbble:
  email: herdin86@gmail.com
  facebook:
  flickr:
  github: herdin
  dockerhub: epubaal
  instagram: _hythloth
  linkedin:
  pinterest:
  rss: Y
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


disqus: https-herdin-github-io
google_analytics: UA-143433153-1
google_adsense: ca-pub-6021900706575667
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://herdin.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# Collect file list in _tags directory to service /tags/...
# collections:
#   tags:
#     output: true
#     permalink: /tags/:path/
#
# defaults:
#   - scope:
#       path: ''
#       type: tags
#     values:
#       layout: tag

timezone: Asia/Seoul

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
# Code HightLight
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  # https://github.com/rouge-ruby/rouge/wiki/List-of-supported-languages-and-lexers
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight-rouge-herdin'

#markdown: kramdown
#highlighter: rouge

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
